### ISSUE TITLE
umls.2017AA.active.st21pv.json not in the dataset

### ISSUE THREAD

**Issue by kbiyani33** [danlou/MedLinker#3]
Hello, so I happened to get everything ready in my VM. I got the dataset from the link you had passed. When I ran :
python medlinker.py
I got the following error:

"""
Traceback (most recent call last):
  File "medlinker.py", line 282, in <module>
    from umls import umls_kb_st21pv as umls_kb
  File "/media/mnt/keshav/medlinker/umls.py", line 56, in <module>
    umls_kb_st21pv = UMLS_KB('umls.2017AA.active.st21pv')
  File "/media/mnt/keshav/medlinker/umls.py", line 10, in __init__
    self.load(umls_version)
  File "/media/mnt/keshav/medlinker/umls.py", line 14, in load
    with open(json_path, 'r') as json_f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/UMLS/umls.2017AA.active.st21pv.json'

"""

Can you please check this out and let me know in case I have missed something, if not where do I find that json file ?

**Comment by danlou** [comment]
Unfortunately I'm not allowed re-distribute UMLS, or even the subset used in MedLinker, according to their license.

This was already discussed in https://github.com/danlou/MedLinker/issues/2#issuecomment-667050097, where you can find more details about generating that file on your own.

Hope it helps.

Best,
Daniel

**Comment by kbiyani33** [comment]
Thanks for your help and the quick response. The downloading of UMLS was a real issue. But was able to fix it eventually.
Cheeers!!
